apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtaller-ingress
  namespace: proyectotaller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: webtaller.franparra.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # IMPORTANTE: Este nombre debe ser IDÃ‰NTICO al de tu archivo servicio-webtaller.yml
            name: servicio-webtaller 
            port:
              number: 30070 # Este es el puerto interno del servicio (no el nodePort 30070)