services:
  webtaller:
    build:
      context: C:\modulos\2DAW\DAW\juan-developer
      dockerfile: deploy/Dockerfile
    ports:
      - "8070:80"
    image: juanalonso-ptaller-webserver:1.0
    container_name: juanalonso-ptaller-webserver
    restart: unless-stopped